version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/www/
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root